vim.loader.enable()
vim.g.repo_root = vim.fs.root(0, ".git")

require("options")
require("ui")
require("keybinds")
require("lsp")
require("colorscheme")
require("multicursor")

require("autocmds.marks")
require("autocmds.yank")
require("autocmds.suspend")
require("autocmds.trailing")
require("autocmds.scrolloff")

require("commands.allman")
require("commands.redir")
require("commands.enter")
require("commands.termhl")
require("commands.rm")
require("commands.deallman")
require("commands.macros")
require("commands.place")
require("commands.chars")
require("commands.treesitter")

require("lz.n").load("lazy")
