keys:
  &users:
    - &emanresu age19gjad6vq8cap0xaf3t4x7v9vx3q5h3gmm3lexza3lcxyv646hdwq8agcf3 # Public age key for any host
  &hosts:
    &framework age1gfqfgrq42gqcc9xm08k65ujw4sydfwygsxx58dldhuy5ruay7ykszccpgg # Public key for framework
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *emanresu
      - *framework
